#Doc http://jekyllrb.com/docs/configuration/
#theme: jekyll-theme
safe: false
baseurl: /test/
defaults:
  - scope:
      path: ""
    values:
      author: "Vetedde"
#SEO
title: "SbmlViewer"
description: "The collection of transformation from SBML files into human readable formats"
liquid:
  error_mode: warn
#Plugins(also we can add whitelist)  
gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
