#Doc http://jekyllrb.com/docs/configuration/
#theme: jekyll-theme
gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
safe: false
#SEO
title: "SbmlViewer"
description: "The collection of transformation from SBML files into human readable formats"
liquid:
  error_mode: warn
yandex_metrika: 44335438
facebook:
  app_id: 597995060394661
twitter:
  username: insysbio
social:
  name: InSysBio
  links:
    - https://www.facebook.com/insysbio
    - https://www.linkedin.com/insysbio
    - https://github.com/insysbio
    - https://twitter.com/insysbio
    - https://insysbio.ru/en
defaults:
  - scope:
      path: ""
    values:
      image: http://sbmlviewer.insilicobio.ru/assets/img/social/default_view.jpg    
#Plugins(also we can add whitelist)  
