#Doc http://jekyllrb.com/docs/configuration/
#theme: jekyll-theme
safe: false
defaults:
  - scope:
      path: ""
    values:
      author: "Vetedde"
#SEO
title: "SbmlViewer"
description: "The collection of transformation from SBML files into human readable formats"
liquid:
  error_mode: warn
social:
  name: InSysBio
  links:
    - https://www.facebook.com/insysbio
    - https://www.linkedin.com/insysbio
    - https://github.com/insysbio
    - https://twitter.com/insysbio
    - https://insysbio.ru/en  
#Plugins(also we can add whitelist)  
gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
